version: 2.1

jobs:
  cypress-local:
    docker:
      - image: cypress/included:12.17.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run Cypress tests (start server & run)
          command: npm run test:cypress
          timeout: 20m

      - store_artifacts:
          path: cypress/videos
          destination: cypress-videos
      - store_artifacts:
          path: cypress/screenshots
          destination: cypress-screenshots

      - store_test_results:
          path: cypress/results

  cypress-live:
    docker:
      - image: cypress/included:12.17.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run Cypress tests against GitHub Pages
          command: |
            if [ -z "$GH_PAGES_URL" ]; then
              echo "Error: GH_PAGES_URL env var is not set. Set it in CircleCI project settings to your GitHub Pages URL (e.g. https://<user>.github.io/<repo>/)";
              exit 1;
            fi
            npm run cy:run:live
          timeout: 20m

      - store_artifacts:
          path: cypress/videos
          destination: cypress-videos-live
      - store_artifacts:
          path: cypress/screenshots
          destination: cypress-screenshots-live

      - store_test_results:
          path: cypress/results

workflows:
  build-and-test:
    jobs:
      - cypress-local
      - cypress-live:
          requires:
            - cypress-local
