version: 2.1

jobs:
  cypress-local:
    docker:
      - image: cypress/included:15.3.0
    working_directory: ~/repo
    steps:
      - checkout

      # Ensure results folder exists
      - run:
          name: Ensure results folder exists
          command: mkdir -p cypress/results

      # Install wait-on to wait for server
      - run:
          name: Install wait-on
          command: npm install -g wait-on

      # Start local server and wait until ready
      - run:
          name: Start local server and wait
          command: |
            npx http-server . -p 8080 &
            npx wait-on http://localhost:8080

      # Run Cypress tests against localhost
      - run:
          name: Run Cypress local tests
          command: npx cypress run --config baseUrl=http://localhost:8080 --reporter junit --reporter-options "mochaFile=cypress/results/results-local-[hash].xml,toConsole=true"
          timeout: 20m

      # Store artifacts and test results
      - store_artifacts:
          path: cypress/videos
          destination: cypress-videos
      - store_artifacts:
          path: cypress/screenshots
          destination: cypress-screenshots
      - store_test_results:
          path: cypress/results

  cypress-live:
    docker:
      - image: cypress/included:15.3.0
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Ensure results folder exists
          command: mkdir -p cypress/results

      - run:
          name: Run Cypress live tests
          command: |
            if [ -z "$GH_PAGES_URL" ]; then
              echo "Error: GH_PAGES_URL env var is not set. Set it in CircleCI project settings.";
              exit 1;
            fi
            npx cypress run --config baseUrl=$GH_PAGES_URL --reporter junit --reporter-options "mochaFile=cypress/results/results-live-[hash].xml,toConsole=true"
          timeout: 20m

      - store_artifacts:
          path: cypress/videos
          destination: cypress-videos-live
      - store_artifacts:
          path: cypress/screenshots
          destination: cypress-screenshots-live
      - store_test_results:
          path: cypress/results

workflows:
  build-and-test:
    jobs:
      - cypress-local
      - cypress-live:
          requires:
            - cypress-local
